In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
df = pd.read_csv('combined_datasets.csv')
df = df.iloc[:, :-3]

In [3]:
df.head(10)

,Brand,Model,YOM,Mileage,Gear,Fuel Type,Engine (cc),Condition,Ad Date,Location,Price,URL,Body Type,Number of Cylinders,Power Steering,Power Shutters,Power Mirrors,Manufacturing Country
0,Audi,A3 Sline,2018,"93,000 km",Automatic,Petrol,1000.0,Registered (Used),"2026 Jun 05, 11:39 am",Colombo,Rs. 14400000,https://riyasewana.com/buy/audi-3-s-line-sale-...,Sedan,3.0,Yes,Yes,Yes,Germany
1,Audi,A1 Sline,2017,"96,000 km",Automatic,Petrol,990.0,Registered (Used),"2026 Jun 06, 10:27 pm",Kandy,Rs. 8650000,https://riyasewana.com/buy/audi-a1-1-0-sale-ka...,Hatchback,3.0,Yes,Yes,Yes,Germany
2,Audi,A1 Highest Spec,2016,"86,000 km",Automatic,Petrol,10000.0,Registered (Used),"2026 Jul 19, 9:58 am",Colombo,Rs. 8200000,https://riyasewana.com/buy/audi-a1-highest-sal...,Hatchback,6.0,Yes,Yes,Yes,Germany
3,Audi,A1,2017,"69,000 km",Automatic,Petrol,1000.0,Registered (Used),"2026 Jul 27, 5:36 pm",Bandaragama,Rs. 8700000,https://riyasewana.com/buy/audi-a1-sale-bandar...,Hatchback,3.0,Yes,Yes,Yes,Germany
4,Audi,A1,2016,"55,000 km",Automatic,Petrol,1000.0,Registered (Used),"2026 Jul 28, 12:06 am",Bandaragama,Rs. 9500000,https://riyasewana.com/buy/audi-a1-sale-bandar...,Hatchback,3.0,Yes,Yes,Yes,Germany
5,Audi,A1,2016,"67,000 km",Automatic,Petrol,999.0,Registered (Used),"2026 May 25, 1:57 pm",Colombo,Rs. 9000000,https://riyasewana.com/buy/audi-a1-sale-colomb...,Hatchback,3.0,Yes,Yes,Yes,Germany
6,Audi,A1,2016,"70,000 km",Automatic,Petrol,NaN,Registered (Used),"2026 May 27, 12:29 pm",Colombo,Rs. 8700000,https://riyasewana.com/buy/audi-a1-sale-colomb...,Hatchback,4.0,Yes,Yes,Yes,Germany
7,Audi,A1,2015,"104,000 km",Automatic,Petrol,1000.0,Registered (Used),"2026 May 28, 2:21 pm",Colombo,Rs. 8200000,https://riyasewana.com/buy/audi-a1-sale-colomb...,Hatchback,3.0,Yes,Yes,Yes,Germany
8,Audi,A1,2018,"116,000 km",Automatic,Petrol,990.0,Registered (Used),"2026 Jun 15, 12:19 pm",Colombo,Rs. 9250000,https://riyasewana.com/buy/audi-a1-sale-colomb...,Hatchback,3.0,Yes,Yes,Yes,Germany
9,Audi,A1,2018,"138,932 km",Automatic,Petrol,1000.0,Registered (Used),"2026 Jun 28, 6:58 pm",Colombo,Rs. 8350000,https://riyasewana.com/buy/audi-a1-sale-colomb...,Hatchback,3.0,Yes,Yes,Yes,Germany

In [4]:
# 2. Create a temporary cleaned series (without altering the original df['Model'] column)
cleaned_models = df['Model'].astype(str).str.strip().str.lower()

# 3. Get unique sorted model names from the temporary series
unique_models = sorted(cleaned_models.unique())

# 4. Display results
print(f"Total Unique Models (cleaned view): {len(unique_models)}\n")
print("List of Unique Models:")
for model in unique_models:
    print(f"- {model}")

Total Unique Models (cleaned view): 945

List of Unique Models:
- 2
- 2 sky active
- 2 skyactive
- 218i msport
- 240 glt 2.3 wagon
- 3
- 3 axela
- 3 skyactive-g
- 316i
- 318i
- 318i e36
- 318i e46
- 318i e46 msport
- 318i f30
- 318i luxury
- 318i m sport
- 318i m sport australian spec
- 318i msport
- 320d
- 320d e46
- 320d f30
- 320d luxury
- 320i
- 323
- 330e m sport
- 335i
- 420d m sport
- 430i
- 430i m sport
- 4dr5
- 520d
- 520d f10
- 520d gt
- 520d m sport
- 520d msport
- 520dmsport
- 520i
- 520i e34
- 523i
- 523i e60
- 523i e60 lci
- 523i e60 m sport
- 523i f10
- 523i luxury
- 523i m sport
- 523i msport
- 525i e39
- 525li m sport
- 528i
- 528i m sport
- 530e
- 530e g30 msport
- 530e individual
- 530e m sport
- 530e m sport individual
- 530e msport
- 530i e60
- 530i g30 m sport
- 535
- 535i
- 6
- 6 gt
- 6 skyactive
- 725d
- 725d m sport
- 725d straight
- 730ld
- 730ld individual spec
- 730li
- 730li individual
- 740e
- 740e i performance
- 740e iperformance m-sport
- 740le
- 740le m sports
- 740le msport plus
- 740le x drive msport
- 740li
- 740li individual
- 940
- 940 gle
- a1
- a1 highest spec
- a1 sline
- a180
- a200
- a200 amg
- a200 amg premium plus
- a200 premium plus
- a3
- a3 advance
- a3 signature
- a3 sline
- a3 sline highest spec
- a3 tfsi s line
- a3 urban style
- a4
- a4 premium
- a4 rs4
- a4 sline
- a5
- a5 coupe
- a5 highest spec
- a5 rs5
- a5 sline
- a5 sline cabriolet
- a5 sline highest spec
- a6
- a6 matrix
- a6 rs6
- a6 sline
- a8
- a8 straight
- allion
- allion 240
- allion 240 anniversary
- allion 240 g
- allion 240 g limited
- allion 260
- allion 260 g
- allion 260 g plus
- allion 260g
- allion g
- allion g plus
- allion nzt 260
- allion nzt260
- aqua
- aqua eagle eye
- aqua eagle eye g grade led
- aqua eagle eye safety edition
- aqua g grade
- aqua g limited
- aqua g sport
- aqua prius c
- aqua s edition anniversary
- aqua s grade
- aqua s limited
- aqua urban
- aqua urban g
- aqua urban g grade
- aqua x urban
- aqua z grade
- astina
- astina sports
- attrage
- axela
- az wagon
- b11 sunny laurel spirit
- b12 trad sunny
- b250e
- beetle swift zc11s
- bf 3v
- bf3p
- bg3p
- bj5p
- bj5p familia
- bluebird
- bluebird sylphy
- bluebird sylphy fg 10
- bluebird sylphy g 11
- bluebird sylphy g11
- butterfly
- c 250
- c 250 amg
- c 300
- c11
- c11 lancer
- c11v
- c12
- c12 wagon
- c160
- c180
- c180 amg
- c180 amg premium plus convertible
- c180 amg special night edition
- c180 avantgarde
- c180 blue efficiency
- c180 kompressor
- c180 kompressor w204
- c180 limousine edition
- c180 premium
- c180 w203 elegance
- c180 w204
- c180 w205
- c180 w205 exclusive
- c200
- c200 amg
- c200 amg line
- c200 amg premium
- c200 amg premium plus
- c200 cabriolet
- c200 exclusive
- c200 premium plus
- c200 premium plus amg line
- c220
- c220 cdi
- c230
- c250
- c300
- c300 bluetech
- c350 e
- c350 spots premium
- c350e
- capella
- carol
- cb 3a
- cb1
- cb2
- cefiro
- cefiro a33
- cefiro a33 excimo
- cefiro j31
- cefiro limited
- chariot
- chr
- chr awd gt turbo
- chr bruno edition ngx10
- chr bruno nxg10
- chr eagle eye ngx10
- chr gt
- chr gt boost impulse
- chr gt bruno
- chr gt led turbo
- chr gt ngx10
- chr gt ngx50
- chr gt trubo
- chr gt turbo
- chr gt turbo bruno
- chr ngx10
- chr ngx10 2wd
- chr ngx10 bruno safety gt turbo
- chr ngx10 eagle eye
- chr ngx10 gt boost impulse
- chr ngx10 gt turbo
- chr ngx10 gt turbo bruno
- chr ngx10 nero
- chr ngx10 turbo
- chr ngx50
- chr ngx50 4wd
- chr ngx50 gt awd
- chr ngx50 gt awd boost impulse
- chr ngx50 gt turbo
- chr ngx50 turbo
- chr nxg10
- chr turbo
- citan tourer 112
- city
- city aria
- city fit
- city fit aria
- city fit ariea
- city rs
- city v tec
- civic
- civic ek3
- civic es 1
- civic es 5
- civic es1
- civic es3 rs
- civic es5
- civic es8
- civic ex
- civic ex tech
- civic ex turbo
- civic ex uk version
- civic fb1
- civic fb2
- civic fd1
- civic fd1 type s
- civic fd3
- civic fd3 uk
- civic fd4
- civic fd4 type s
- civic fk6 sr
- civic fk6 tech
- civic fk7
- civic fk7 vtec turbo
- civic grand
- civic sedan tech
- civic sr
- civic sr uk
- civic tach
- civic tech
- ck2a
- cla 180
- cla 180 amg
- cla 180 amg premium plus
- cla 180 cla220 amg
- cla 200
- cla 200 amg premium plus
- cla 200 premium plus
- clipper
- clipper cvt pw
- clipper cvt rpm
- clipper da64
- clipper dr17v
- clipper dx
- clipper dx gl
- clipper dx pa limited
- clipper dxgl
- clipper full join
- clipper full join gx
- clipper gl
- clipper gl cvt led
- clipper gl led rpm
- clipper gl pw
- clipper gl rpm meter
- clipper gx
- clipper gx join
- clipper nv-100
- clipper nv100
- clipper nv100 dx
- clipper nv100 gx gl
- clipper nv100 rio
- clipper pa limited
- clipper pc
- clipper pc led
- clipper pc limited
- clipper pw
- clipper pw pm safety
- clipper pw safety
- clipper rio
- clipper rio wagon
- clipper wagon
- clipperpa limited
- clipperpw pm led safety
- cls 350
- cls350
- colt
- corolla
- corolla 103
- corolla 110
- corolla 110 x grade
- corolla 111
- corolla 121
- corolla 121 g grade
- corolla 121 g limited
- corolla 121 lx limited
- corolla 121 x grade
- corolla 141
- corolla 141 gli
- corolla 141 limited edition
- corolla 141 lx
- corolla 2
- corolla 2 el51
- corolla 2 windy el 41
- corolla 2 windy el30
- corolla ae100
- corolla ae110
- corolla ae110 sprinter
- corolla ae111
- corolla axio
- corolla ce100
- corolla ce106
- corolla ce110
- corolla ce121
- corolla ce90
- corolla corsa
- corolla dx 72
- corolla dx ke72
- corolla dx ke74
- corolla ee 111
- corolla ee111
- corolla ee96
- corolla ke 55
- corolla ke50
- corolla ke72
- corolla ke74
- corolla nze121
- corolla wxb
- corolla wxb sport
- corona premio
- corona premio g grade
- crv
- crv australian
- crv ex masterpiece
- crv masterpiece
- crv rd1
- crv rd5
- crv re2
- crv re4
- crv rm 1
- crv rm 2
- crv rm1
- crv rm2
- crv rm4
- crv vtil
- crv vtis
- cs1
- cs3
- dayz
- dayz high way star
- dayz high way star pro pilot
- dayz highway star
- dayz highway star g turbo pro pilot edition
- dayz highway star pro pilot
- dayz highway star propilot
- dayz highway star turbo g grade
- dayz highway star x
- dayz highway star x propilot
- dayz s grade
- dayz x
- dayz x b43w
- dayz x grade
- dbabk5p
- demio
- demio japan
- doctor sunny
- doctor sunny fb13
- doctor sunny super saloon
- dutsun sunny hb310
- e 240
- e-hb12 sunny
- e180
- e180 amg line
- e200
- e200 amg premium plus
- e200 avantgarde
- e200 blue efficiency
- e200 cgi avantgarde
- e200 kompressor
- e200 night edition amg line
- e200 w212
- e200 w213
- e220
- e220 amg sport
- e220 cdi
- e220 cdi w212
- e240
- e250
- e250 cabriolet
- e250 cgi w212 avantgrade
- e280
- e300
- e300 bluetec hybrid
- e300 bluetec hybrid amg
- e300 coupe amg
- e300 night edition
- e350
- e350e
- e350e amg
- e350e amg premium plus
- ek space
- ek space g
- ek space hybrid
- ek wagon
- ek wagon b21dayz
- ek wagon custom
- ek wagon g grade
- ek wagon g grade dayz
- ek wagon m
- ek wagon m grade
- ek wagon r safety
- ek x cross
- ek x cross g
- ek x cross hybrid
- ek x cross turbo
- ek x ev limited
- ek x g premium
- ek-cross g premium
- ekx
- every
- every da 17
- every da 17 w wagon
- every da 52
- every da17
- every da17 full
- every da17 full join
- every da17 safety join
- every da17v
- every da18v
- every da62
- every da64
- every da64 wagon turbo
- every da64v
- every da64v full join
- every da7
- every full join
- every full join turbo
- every join
- every join turbo
- every pa limited
- every pc da17
- every pc limited
- every pc ltd
- every safety
- every semi join
- every turbo
- every wagon
- every wagon pz
- every wagon pz turbo
- every wagon turbo
- evolution
- evolution 6
- evolution 7
- ex
- f-s typeport coupe
- familia
- familia 323
- familia 323 bg3p
- familia 323 bg5p
- familia 323 bj5
- familia 323 lx
- familia 626
- familia bftp
- familia bg3p
- familia bg5p
- familia bj3
- familia bj3p
- familia bj5
- familia bj5p
- familia bj5w
- familia butterfly
- familia efi
- familia limited
- familia mr 90
- familia wagon
- fb12 trad sunny super saloon
- fb13 doctor sunny
- fb13 sunny
- fb14 sunny
- fb15 sunny
- fit
- fit aria
- fit aria gd8
- fit aria gd8 city
- fit gd1
- fit ge6
- fit gp1
- fit gp1 10th anniversary
- fit gp1 navi
- fit gp1 navi premium
- fit gp3 freed
- fit gp4
- fit gp5
- fit gp5 l grade
- fit gp5 l safety
- fit gp5 s
- fit gp5 s grade
- fit gp5 s grade safety
- fit shuttle
- fit shuttle gp2
- fit shuttle special edition
- flair
- fronx
- fronx alpha
- fronx alpha 1l
- fronx alpha at
- fronx alpha dt
- fronx alpha turbo
- fronx v grade
- galant
- galant sport
- gl wagon
- glx
- grace
- grace ex
- grace ex limited edition
- grace ex sensing
- grace rs sensing
- hb12 trad sunny
- i7 m sport
- i8
- i8 roadster
- l light
- lancer
- lancer box
- lancer box 5fwd
- lancer box 5fwrd
- lancer box b11 c12
- lancer c s1
- lancer c11
- lancer c12
- lancer cb
- lancer cb1
- lancer cb2
- lancer cb2a
- lancer cb3a
- lancer cb8
- lancer ck1
- lancer ck1a
- lancer ck1a japan
- lancer ck2
- lancer ck2 doch
- lancer ck2a
- lancer cs 5
- lancer cs1
- lancer cs1 glx
- lancer cs1glx
- lancer cs2
- lancer cs2 glx
- lancer cs3
- lancer cs3 glx
- lancer evolution 6
- lancer evolution 7 gta
- lancer ex
- lancer ex gt
- lancer flat light
- lancer flat light gl
- lancer glx
- lancer glx cs1
- lancer wagon
- lancer wagon el
- libero
- march
- march ak12
- march ak12 japan
- march ak12 limited
- march beetle ak12
- march bk12 sport 1380 cc
- march hk
- march hk11
- march k10
- march k11
- march k12
- march k13
- minica
- mirage
- mister lx
- mitsubishi
- mmc wagon
- mr 90
- n16 bluebird sylphy
- n16 fg10 bluebird sylphy
- n16 n17 sunny
- n16 sunny
- n16 sunny n17
- n16 sunny n17 super saloon
- n16 sunny super saloon
- n16 sunny super saloon japan
- n17 bluebird sylphy
- premio
- premio 240
- premio 240g
- premio 260
- premio 260 g superior
- premio g superior
- presea
- prius
- prius 20
- prius 20 2nd gen
- prius 2nd gen
- prius 2nd generation
- prius 3rd gen
- prius 3rd gen s grade
- prius 4th gen
- prius alpha
- prius alpha cx
- prius g grade
- prius g grade 3rd generation
- prius g sport
- prius g touring
- prius g touring solar
- prius led
- prius nhw20
- prius phv
- prius s grade
- prius s led
- prius s led my coordination
- prius s limited
- prius s touring
- protege
- pulsar
- pulsar cj1
- pulsar cjfb14 limited edition
- pulsar fn 15
- pulsar fn15
- pulsar fn15fb15
- pulsar n14
- pulsar sunny fb14
- raize
- raize  z
- raize 1 2 l
- raize 1 2l
- raize 1 2l z
- raize 1200
- raize 1200 z
- raize g
- raize g premium
- raize hybrid
- raize hybrid bsm
- raize hybrid z
- raize turbo
- raize x
- raize z
- raize z  apple 4 way
- raize z  bsm
- raize z  hybrid
- raize z  japan
- raize z 1 2l bsm
- raize z 1200
- raize z 1200 bsm
- raize z 1200 hybrid
- raize z bsm
- raize z great 1000 japan
- raize z highst gradejapan
- raize z hybrid
- raize z hybrid 1200cc
- raize z hybrid 4 way cam
- raize z japan
- raize z parking
- roox
- roox g turbo highway
- roox g turbo propilot
- roox highway star
- roox highway star g propilot
- roox highway star g turbo
- roox highway star pro filight
- roox highway star pro pilot
- roox highway star x
- roox highway star x pro pilot
- roox highway star xs
- roox propilot
- roox x grade
- rx-8
- rx-8 limited edition
- s 400
- s 60
- s 70
- s type
- s300
- s300 h class
- s300 w221 lwb
- s320
- s320 long wheel
- s350
- s350 w220 lwb
- s40
- s40 t4
- s400
- s400 chogm
- s400 lwb
- s580e
- s60
- s60 t6
- s80
- s90 inscription t5i
- saloon
- sigma galant gl
- skyactiv
- slc180
- smart fortwo
- special
- sport
- starlet
- starlet efi
- starlet ep71
- starlet ep82
- starlet ep82 turbo
- starlet ep91
- starlet glanza conversion
- starlet glanza v
- starlet gt turbo
- starlet np 70
- starlet np 90
- starlet np90
- starlet reflet f ep91
- starlet reflet limited
- sunny
- sunny b11
- sunny b12
- sunny b13
- sunny b310
- sunny bluebird
- sunny bluebird sylphy
- sunny datsun b310
- sunny ex saloon
- sunny fb12
- sunny fb13 super saloon
- sunny fb13 super saloon 25th anniversary
- sunny fb14
- sunny fb14 ex saloon
- sunny fb14 super saloon
- sunny fb15
- sunny fb15 ex saloon
- sunny fb15 super saloon
- sunny hb11
- sunny hb12
- sunny n17
- sunny n17 ex saloon
- sunny sb13
- sunny sb14
- sunny wingroad wfy11
- sunny y11
- swift
- swift beatle zc71s
- swift beetle
- swift beetle zc71s
- swift bettle
- swift center antanna
- swift center antenna
- swift ht51s center antenna
- swift kei
- swift mz
- swift rs
- swift rs 4way
- swift rs hybrid
- swift rs safety
- swift rs special edition
- swift rs turbo
- swift rs turbo safety
- swift splash
- swift sport
- tiida
- tiida cvt
- tiida hatchback
- tiida japan
- tiida latio
- toppo
- towny
- trad sunny
- trad sunny b12
- trad sunny fb12
- trad sunny hb12
- tredia
- vezel
- vezel orange
- vezel premium
- vezel rs
- vezel rs premium
- vezel rs sensing
- vezel rs sensing led
- vezel rs sensing premium
- vezel ru3
- vezel x
- vezel x hunt
- vezel z
- vezel z 4wd
- vezel z grade
- vezel z grade orange
- vezel z limited
- vezel z orange
- vezel z play
- vezel z play moonroof
- vezel z premium
- vezel z premium grade 5
- vezel z premium limited black edition
- vezel z premium plus
- vezel z rs led
- vitz
- vitz dba scp90
- vitz edition
- vitz edition 1
- vitz edition 2
- vitz edition 2 special grade
- vitz edition 3
- vitz ill
- vitz ksp 130
- vitz ksp 90
- vitz ksp130
- vitz ksp130 edition 1
- vitz ksp130 safety
- vitz ksp90
- vitz led edition
- vitz led safety edition 3
- vitz limited edition
- vitz rs
- vitz safety
- vitz safety edition led
- vitz scp 90
- vitz scp10
- vitz scp90
- vitz scp90 rs
- vitz u grade
- vitz u grade ksp90
- vitz u grade scp 10
- w 210
- w 210 190 baby
- w 210 e270
- w123
- w124
- w201 190d
- w202
- w202 250 d
- w202 c200
- w203
- w203 c180 komprossor
- w203 c200 kompressor
- w203 c230 sport
- w203 c240
- w204 c180 cgi
- w210
- w210 e200
- w210 e240
- w210 elegance
- w210-e230
- w211
- w211 e200
- w211 e200 amg
- w212 e200
- w212 e250
- w220
- w220 s-class
- w220 s280
- wagon
- wagon r
- wagon r custom
- wagon r custom z
- wagon r custom z hybrid
- wagon r custom zx
- wagon r custom zx 360 cam
- wagon r fx
- wagon r fx premium
- wagon r fx safety
- wagon r fxs hybrid
- wagon r fz
- wagon r fz premium
- wagon r fz safety
- wagon r japan
- wagon r stingray
- wagon r stingray j style
- wagon r stingray safety
- wagon r stingray turbo
- wagon r zl
- wagon r zx
- wagon r zx custom
- wagon r zx hybrid
- x c40
- x type
- xf
- xpandar cross
- yaris
- yaris  g
- yaris  x
- yaris active
- yaris ativ
- yaris ativ gr
- yaris ativ premium luxury
- yaris ativ s grade
- yaris cross
- yaris g
- yaris g  led
- yaris g led
- yaris g led highest spec
- yaris g limited
- yaris led limited edition g
- yaris safety edition
- yaris special edition
- yaris uk
- yaris x
- yaris x  limited
- yaris x grade
- yaris x limited
- yaris x safety
- yaris x safety spec

In [5]:
print(unique_models)

['2', '2 sky active', '2 skyactive', '218i msport', '240 glt 2.3 wagon', '3', '3 axela', '3 skyactive-g', '316i', '318i', '318i e36', '318i e46', '318i e46 msport', '318i f30', '318i luxury', '318i m sport', '318i m sport australian spec', '318i msport', '320d', '320d e46', '320d f30', '320d luxury', '320i', '323', '330e m sport', '335i', '420d m sport', '430i', '430i m sport', '4dr5', '520d', '520d f10', '520d gt', '520d m sport', '520d msport', '520dmsport', '520i', '520i e34', '523i', '523i e60', '523i e60 lci', '523i e60 m sport', '523i f10', '523i luxury', '523i m sport', '523i msport', '525i e39', '525li m sport', '528i', '528i m sport', '530e', '530e g30 msport', '530e individual', '530e m sport', '530e m sport individual', '530e msport', '530i e60', '530i g30 m sport', '535', '535i', '6', '6 gt', '6 skyactive', '725d', '725d m sport', '725d straight', '730ld', '730ld individual spec', '730li', '730li individual', '740e', '740e i performance', '740e iperformance m-sport', '740le', '740le m sports', '740le msport plus', '740le x drive msport', '740li', '740li individual', '940', '940 gle', 'a1', 'a1 highest spec', 'a1 sline', 'a180', 'a200', 'a200 amg', 'a200 amg premium plus', 'a200 premium plus', 'a3', 'a3 advance', 'a3 signature', 'a3 sline', 'a3 sline highest spec', 'a3 tfsi s line', 'a3 urban style', 'a4', 'a4 premium', 'a4 rs4', 'a4 sline', 'a5', 'a5 coupe', 'a5 highest spec', 'a5 rs5', 'a5 sline', 'a5 sline cabriolet', 'a5 sline highest spec', 'a6', 'a6 matrix', 'a6 rs6', 'a6 sline', 'a8', 'a8 straight', 'allion', 'allion 240', 'allion 240 anniversary', 'allion 240 g', 'allion 240 g limited', 'allion 260', 'allion 260 g', 'allion 260 g plus', 'allion 260g', 'allion g', 'allion g plus', 'allion nzt 260', 'allion nzt260', 'aqua', 'aqua eagle eye', 'aqua eagle eye g grade led', 'aqua eagle eye safety edition', 'aqua g grade', 'aqua g limited', 'aqua g sport', 'aqua prius c', 'aqua s edition anniversary', 'aqua s grade', 'aqua s limited', 'aqua urban', 'aqua urban g', 'aqua urban g grade', 'aqua x urban', 'aqua z grade', 'astina', 'astina sports', 'attrage', 'axela', 'az wagon', 'b11 sunny laurel spirit', 'b12 trad sunny', 'b250e', 'beetle swift zc11s', 'bf 3v', 'bf3p', 'bg3p', 'bj5p', 'bj5p familia', 'bluebird', 'bluebird sylphy', 'bluebird sylphy fg 10', 'bluebird sylphy g 11', 'bluebird sylphy g11', 'butterfly', 'c 250', 'c 250 amg', 'c 300', 'c11', 'c11 lancer', 'c11v', 'c12', 'c12 wagon', 'c160', 'c180', 'c180 amg', 'c180 amg premium plus convertible', 'c180 amg special night edition', 'c180 avantgarde', 'c180 blue efficiency', 'c180 kompressor', 'c180 kompressor w204', 'c180 limousine edition', 'c180 premium', 'c180 w203 elegance', 'c180 w204', 'c180 w205', 'c180 w205 exclusive', 'c200', 'c200 amg', 'c200 amg line', 'c200 amg premium', 'c200 amg premium plus', 'c200 cabriolet', 'c200 exclusive', 'c200 premium plus', 'c200 premium plus amg line', 'c220', 'c220 cdi', 'c230', 'c250', 'c300', 'c300 bluetech', 'c350 e', 'c350 spots premium', 'c350e', 'capella', 'carol', 'cb 3a', 'cb1', 'cb2', 'cefiro', 'cefiro a33', 'cefiro a33 excimo', 'cefiro j31', 'cefiro limited', 'chariot', 'chr', 'chr awd gt turbo', 'chr bruno edition ngx10', 'chr bruno nxg10', 'chr eagle eye ngx10', 'chr gt', 'chr gt boost impulse', 'chr gt bruno', 'chr gt led turbo', 'chr gt ngx10', 'chr gt ngx50', 'chr gt trubo', 'chr gt turbo', 'chr gt turbo bruno', 'chr ngx10', 'chr ngx10 2wd', 'chr ngx10 bruno safety gt turbo', 'chr ngx10 eagle eye', 'chr ngx10 gt boost impulse', 'chr ngx10 gt turbo', 'chr ngx10 gt turbo bruno', 'chr ngx10 nero', 'chr ngx10 turbo', 'chr ngx50', 'chr ngx50 4wd', 'chr ngx50 gt awd', 'chr ngx50 gt awd boost impulse', 'chr ngx50 gt turbo', 'chr ngx50 turbo', 'chr nxg10', 'chr turbo', 'citan tourer 112', 'city', 'city aria', 'city fit', 'city fit aria', 'city fit ariea', 'city rs', 'city v tec', 'civic', 'civic ek3', 'civic es 1', 'civic es 5', 'civic es1', 'civic es3 rs', 'civic es5', 'civic es8', 'civic ex', 'civic ex tech', 'civic ex turbo', 'civic ex uk version', 'civic fb1', 'civic fb2', 'civic fd1', 'civic fd1 type s', 'civic fd3', 'civic fd3 uk', 'civic fd4', 'civic fd4 type s', 'civic fk6 sr', 'civic fk6 tech', 'civic fk7', 'civic fk7 vtec turbo', 'civic grand', 'civic sedan tech', 'civic sr', 'civic sr uk', 'civic tach', 'civic tech', 'ck2a', 'cla 180', 'cla 180 amg', 'cla 180 amg premium plus', 'cla 180 cla220 amg', 'cla 200', 'cla 200 amg premium plus', 'cla 200 premium plus', 'clipper', 'clipper cvt pw', 'clipper cvt rpm', 'clipper da64', 'clipper dr17v', 'clipper dx', 'clipper dx gl', 'clipper dx pa limited', 'clipper dxgl', 'clipper full join', 'clipper full join gx', 'clipper gl', 'clipper gl cvt led', 'clipper gl led rpm', 'clipper gl pw', 'clipper gl rpm meter', 'clipper gx', 'clipper gx join', 'clipper nv-100', 'clipper nv100', 'clipper nv100 dx', 'clipper nv100 gx gl', 'clipper nv100 rio', 'clipper pa limited', 'clipper pc', 'clipper pc led', 'clipper pc limited', 'clipper pw', 'clipper pw pm safety', 'clipper pw safety', 'clipper rio', 'clipper rio wagon', 'clipper wagon', 'clipperpa limited', 'clipperpw pm led safety', 'cls 350', 'cls350', 'colt', 'corolla', 'corolla 103', 'corolla 110', 'corolla 110 x grade', 'corolla 111', 'corolla 121', 'corolla 121 g grade', 'corolla 121 g limited', 'corolla 121 lx limited', 'corolla 121 x grade', 'corolla 141', 'corolla 141 gli', 'corolla 141 limited edition', 'corolla 141 lx', 'corolla 2', 'corolla 2 el51', 'corolla 2 windy el 41', 'corolla 2 windy el30', 'corolla ae100', 'corolla ae110', 'corolla ae110 sprinter', 'corolla ae111', 'corolla axio', 'corolla ce100', 'corolla ce106', 'corolla ce110', 'corolla ce121', 'corolla ce90', 'corolla corsa', 'corolla dx 72', 'corolla dx ke72', 'corolla dx ke74', 'corolla ee 111', 'corolla ee111', 'corolla ee96', 'corolla ke 55', 'corolla ke50', 'corolla ke72', 'corolla ke74', 'corolla nze121', 'corolla wxb', 'corolla wxb sport', 'corona premio', 'corona premio g grade', 'crv', 'crv australian', 'crv ex masterpiece', 'crv masterpiece', 'crv rd1', 'crv rd5', 'crv re2', 'crv re4', 'crv rm 1', 'crv rm 2', 'crv rm1', 'crv rm2', 'crv rm4', 'crv vtil', 'crv vtis', 'cs1', 'cs3', 'dayz', 'dayz high way star', 'dayz high way star pro pilot', 'dayz highway star', 'dayz highway star g turbo pro pilot edition', 'dayz highway star pro pilot', 'dayz highway star propilot', 'dayz highway star turbo g grade', 'dayz highway star x', 'dayz highway star x propilot', 'dayz s grade', 'dayz x', 'dayz x b43w', 'dayz x grade', 'dbabk5p', 'demio', 'demio japan', 'doctor sunny', 'doctor sunny fb13', 'doctor sunny super saloon', 'dutsun sunny hb310', 'e 240', 'e-hb12 sunny', 'e180', 'e180 amg line', 'e200', 'e200 amg premium plus', 'e200 avantgarde', 'e200 blue efficiency', 'e200 cgi avantgarde', 'e200 kompressor', 'e200 night edition amg line', 'e200 w212', 'e200 w213', 'e220', 'e220 amg sport', 'e220 cdi', 'e220 cdi w212', 'e240', 'e250', 'e250 cabriolet', 'e250 cgi w212 avantgrade', 'e280', 'e300', 'e300 bluetec hybrid', 'e300 bluetec hybrid amg', 'e300 coupe amg', 'e300 night edition', 'e350', 'e350e', 'e350e amg', 'e350e amg premium plus', 'ek space', 'ek space g', 'ek space hybrid', 'ek wagon', 'ek wagon b21dayz', 'ek wagon custom', 'ek wagon g grade', 'ek wagon g grade dayz', 'ek wagon m', 'ek wagon m grade', 'ek wagon r safety', 'ek x cross', 'ek x cross g', 'ek x cross hybrid', 'ek x cross turbo', 'ek x ev limited', 'ek x g premium', 'ek-cross g premium', 'ekx', 'every', 'every da 17', 'every da 17 w wagon', 'every da 52', 'every da17', 'every da17 full', 'every da17 full join', 'every da17 safety join', 'every da17v', 'every da18v', 'every da62', 'every da64', 'every da64 wagon turbo', 'every da64v', 'every da64v full join', 'every da7', 'every full join', 'every full join turbo', 'every join', 'every join turbo', 'every pa limited', 'every pc da17', 'every pc limited', 'every pc ltd', 'every safety', 'every semi join', 'every turbo', 'every wagon', 'every wagon pz', 'every wagon pz turbo', 'every wagon turbo', 'evolution', 'evolution 6', 'evolution 7', 'ex', 'f-s typeport coupe', 'familia', 'familia 323', 'familia 323 bg3p', 'familia 323 bg5p', 'familia 323 bj5', 'familia 323 lx', 'familia 626', 'familia bftp', 'familia bg3p', 'familia bg5p', 'familia bj3', 'familia bj3p', 'familia bj5', 'familia bj5p', 'familia bj5w', 'familia butterfly', 'familia efi', 'familia limited', 'familia mr 90', 'familia wagon', 'fb12 trad sunny super saloon', 'fb13 doctor sunny', 'fb13 sunny', 'fb14 sunny', 'fb15 sunny', 'fit', 'fit aria', 'fit aria gd8', 'fit aria gd8 city', 'fit gd1', 'fit ge6', 'fit gp1', 'fit gp1 10th anniversary', 'fit gp1 navi', 'fit gp1 navi premium', 'fit gp3 freed', 'fit gp4', 'fit gp5', 'fit gp5 l grade', 'fit gp5 l safety', 'fit gp5 s', 'fit gp5 s grade', 'fit gp5 s grade safety', 'fit shuttle', 'fit shuttle gp2', 'fit shuttle special edition', 'flair', 'fronx', 'fronx alpha', 'fronx alpha 1l', 'fronx alpha at', 'fronx alpha dt', 'fronx alpha turbo', 'fronx v grade', 'galant', 'galant sport', 'gl wagon', 'glx', 'grace', 'grace ex', 'grace ex limited edition', 'grace ex sensing', 'grace rs sensing', 'hb12 trad sunny', 'i7 m sport', 'i8', 'i8 roadster', 'l light', 'lancer', 'lancer box', 'lancer box 5fwd', 'lancer box 5fwrd', 'lancer box b11 c12', 'lancer c s1', 'lancer c11', 'lancer c12', 'lancer cb', 'lancer cb1', 'lancer cb2', 'lancer cb2a', 'lancer cb3a', 'lancer cb8', 'lancer ck1', 'lancer ck1a', 'lancer ck1a japan', 'lancer ck2', 'lancer ck2 doch', 'lancer ck2a', 'lancer cs 5', 'lancer cs1', 'lancer cs1 glx', 'lancer cs1glx', 'lancer cs2', 'lancer cs2 glx', 'lancer cs3', 'lancer cs3 glx', 'lancer evolution 6', 'lancer evolution 7 gta', 'lancer ex', 'lancer ex gt', 'lancer flat light', 'lancer flat light gl', 'lancer glx', 'lancer glx cs1', 'lancer wagon', 'lancer wagon el', 'libero', 'march', 'march ak12', 'march ak12 japan', 'march ak12 limited', 'march beetle ak12', 'march bk12 sport 1380 cc', 'march hk', 'march hk11', 'march k10', 'march k11', 'march k12', 'march k13', 'minica', 'mirage', 'mister lx', 'mitsubishi', 'mmc wagon', 'mr 90', 'n16 bluebird sylphy', 'n16 fg10 bluebird sylphy', 'n16 n17 sunny', 'n16 sunny', 'n16 sunny n17', 'n16 sunny n17 super saloon', 'n16 sunny super saloon', 'n16 sunny super saloon japan', 'n17 bluebird sylphy', 'premio', 'premio 240', 'premio 240g', 'premio 260', 'premio 260 g superior', 'premio g superior', 'presea', 'prius', 'prius 20', 'prius 20 2nd gen', 'prius 2nd gen', 'prius 2nd generation', 'prius 3rd gen', 'prius 3rd gen s grade', 'prius 4th gen', 'prius alpha', 'prius alpha cx', 'prius g grade', 'prius g grade 3rd generation', 'prius g sport', 'prius g touring', 'prius g touring solar', 'prius led', 'prius nhw20', 'prius phv', 'prius s grade', 'prius s led', 'prius s led my coordination', 'prius s limited', 'prius s touring', 'protege', 'pulsar', 'pulsar cj1', 'pulsar cjfb14 limited edition', 'pulsar fn 15', 'pulsar fn15', 'pulsar fn15fb15', 'pulsar n14', 'pulsar sunny fb14', 'raize', 'raize  z', 'raize 1 2 l', 'raize 1 2l', 'raize 1 2l z', 'raize 1200', 'raize 1200 z', 'raize g', 'raize g premium', 'raize hybrid', 'raize hybrid bsm', 'raize hybrid z', 'raize turbo', 'raize x', 'raize z', 'raize z  apple 4 way', 'raize z  bsm', 'raize z  hybrid', 'raize z  japan', 'raize z 1 2l bsm', 'raize z 1200', 'raize z 1200 bsm', 'raize z 1200 hybrid', 'raize z bsm', 'raize z great 1000 japan', 'raize z highst gradejapan', 'raize z hybrid', 'raize z hybrid 1200cc', 'raize z hybrid 4 way cam', 'raize z japan', 'raize z parking', 'roox', 'roox g turbo highway', 'roox g turbo propilot', 'roox highway star', 'roox highway star g propilot', 'roox highway star g turbo', 'roox highway star pro filight', 'roox highway star pro pilot', 'roox highway star x', 'roox highway star x pro pilot', 'roox highway star xs', 'roox propilot', 'roox x grade', 'rx-8', 'rx-8 limited edition', 's 400', 's 60', 's 70', 's type', 's300', 's300 h class', 's300 w221 lwb', 's320', 's320 long wheel', 's350', 's350 w220 lwb', 's40', 's40 t4', 's400', 's400 chogm', 's400 lwb', 's580e', 's60', 's60 t6', 's80', 's90 inscription t5i', 'saloon', 'sigma galant gl', 'skyactiv', 'slc180', 'smart fortwo', 'special', 'sport', 'starlet', 'starlet efi', 'starlet ep71', 'starlet ep82', 'starlet ep82 turbo', 'starlet ep91', 'starlet glanza conversion', 'starlet glanza v', 'starlet gt turbo', 'starlet np 70', 'starlet np 90', 'starlet np90', 'starlet reflet f ep91', 'starlet reflet limited', 'sunny', 'sunny b11', 'sunny b12', 'sunny b13', 'sunny b310', 'sunny bluebird', 'sunny bluebird sylphy', 'sunny datsun b310', 'sunny ex saloon', 'sunny fb12', 'sunny fb13 super saloon', 'sunny fb13 super saloon 25th anniversary', 'sunny fb14', 'sunny fb14 ex saloon', 'sunny fb14 super saloon', 'sunny fb15', 'sunny fb15 ex saloon', 'sunny fb15 super saloon', 'sunny hb11', 'sunny hb12', 'sunny n17', 'sunny n17 ex saloon', 'sunny sb13', 'sunny sb14', 'sunny wingroad wfy11', 'sunny y11', 'swift', 'swift beatle zc71s', 'swift beetle', 'swift beetle zc71s', 'swift bettle', 'swift center antanna', 'swift center antenna', 'swift ht51s center antenna', 'swift kei', 'swift mz', 'swift rs', 'swift rs 4way', 'swift rs hybrid', 'swift rs safety', 'swift rs special edition', 'swift rs turbo', 'swift rs turbo safety', 'swift splash', 'swift sport', 'tiida', 'tiida cvt', 'tiida hatchback', 'tiida japan', 'tiida latio', 'toppo', 'towny', 'trad sunny', 'trad sunny b12', 'trad sunny fb12', 'trad sunny hb12', 'tredia', 'vezel', 'vezel orange', 'vezel premium', 'vezel rs', 'vezel rs premium', 'vezel rs sensing', 'vezel rs sensing led', 'vezel rs sensing premium', 'vezel ru3', 'vezel x', 'vezel x hunt', 'vezel z', 'vezel z 4wd', 'vezel z grade', 'vezel z grade orange', 'vezel z limited', 'vezel z orange', 'vezel z play', 'vezel z play moonroof', 'vezel z premium', 'vezel z premium grade 5', 'vezel z premium limited black edition', 'vezel z premium plus', 'vezel z rs led', 'vitz', 'vitz dba scp90', 'vitz edition', 'vitz edition 1', 'vitz edition 2', 'vitz edition 2 special grade', 'vitz edition 3', 'vitz ill', 'vitz ksp 130', 'vitz ksp 90', 'vitz ksp130', 'vitz ksp130 edition 1', 'vitz ksp130 safety', 'vitz ksp90', 'vitz led edition', 'vitz led safety edition 3', 'vitz limited edition', 'vitz rs', 'vitz safety', 'vitz safety edition led', 'vitz scp 90', 'vitz scp10', 'vitz scp90', 'vitz scp90 rs', 'vitz u grade', 'vitz u grade ksp90', 'vitz u grade scp 10', 'w 210', 'w 210 190 baby', 'w 210 e270', 'w123', 'w124', 'w201 190d', 'w202', 'w202 250 d', 'w202 c200', 'w203', 'w203 c180 komprossor', 'w203 c200 kompressor', 'w203 c230 sport', 'w203 c240', 'w204 c180 cgi', 'w210', 'w210 e200', 'w210 e240', 'w210 elegance', 'w210-e230', 'w211', 'w211 e200', 'w211 e200 amg', 'w212 e200', 'w212 e250', 'w220', 'w220 s-class', 'w220 s280', 'wagon', 'wagon r', 'wagon r custom', 'wagon r custom z', 'wagon r custom z hybrid', 'wagon r custom zx', 'wagon r custom zx 360 cam', 'wagon r fx', 'wagon r fx premium', 'wagon r fx safety', 'wagon r fxs hybrid', 'wagon r fz', 'wagon r fz premium', 'wagon r fz safety', 'wagon r japan', 'wagon r stingray', 'wagon r stingray j style', 'wagon r stingray safety', 'wagon r stingray turbo', 'wagon r zl', 'wagon r zx', 'wagon r zx custom', 'wagon r zx hybrid', 'x c40', 'x type', 'xf', 'xpandar cross', 'yaris', 'yaris  g', 'yaris  x', 'yaris active', 'yaris ativ', 'yaris ativ gr', 'yaris ativ premium luxury', 'yaris ativ s grade', 'yaris cross', 'yaris g', 'yaris g  led', 'yaris g led', 'yaris g led highest spec', 'yaris g limited', 'yaris led limited edition g', 'yaris safety edition', 'yaris special edition', 'yaris uk', 'yaris x', 'yaris x  limited', 'yaris x grade', 'yaris x limited', 'yaris x safety', 'yaris x safety spec']

In [6]:
output_txt = 'unique_models.txt'
with open(output_txt, 'w', encoding='utf-8') as f:
    for model in unique_models:
        f.write(f"{model}\n")

print(f"Successfully saved {len(unique_models)} unique models to '{output_txt}'!")

Successfully saved 945 unique models to 'unique_models.txt'!

In [7]:
df['Model_cleaned'] = (
    df['Model']
    .astype(str)
    .str.strip()
    .str.lower()
    .str.replace(r'\s+', '', regex=True)
)

In [8]:
models = sorted(df['Model_cleaned'].unique())

In [9]:
print(len(models))

901

In [10]:
df['Mileage'] = (
    df['Mileage']
    .astype(str)
    .str.replace('km', '', case=False)
    .str.replace(',', '', regex=True)
    .str.strip()
)

df['Mileage_numeric'] = pd.to_numeric(df['Mileage'], errors='coerce')

# 3. Optional: Inspect the cleaned column and its data type
print(df[['Mileage_numeric']].info())
print(df['Mileage_numeric'].head(10))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6436 entries, 0 to 6435
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Mileage_numeric  6418 non-null   float64
dtypes: float64(1)
memory usage: 50.4 KB
None
0     93000.0
1     96000.0
2     86000.0
3     69000.0
4     55000.0
5     67000.0
6     70000.0
7    104000.0
8    116000.0
9    138932.0
Name: Mileage_numeric, dtype: float64

In [11]:
# 2. Clean and convert 'Price' to numeric:
# - Convert to string, remove 'Rs.' (case-insensitive), remove commas, and strip whitespace
# - Convert to numeric using pd.to_numeric, which automatically coerces text like 'Negotiable' into NaN
df['Price'] = (
    df['Price']
    .astype(str)
    .str.replace('Rs.', '', case=False)
    .str.replace(',', '', regex=True)
    .str.strip()
)

df['Price_numeric'] = pd.to_numeric(df['Price'], errors='coerce')

# 3. Optional: Check the result and data type
print(df[['Price_numeric']].info())
print(df['Price_numeric'].head(15))

# Save the updated dataframe if needed
# df.to_csv('cleaned_datasets.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6436 entries, 0 to 6435
Data columns (total 1 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Price_numeric  4996 non-null   float64
dtypes: float64(1)
memory usage: 50.4 KB
None
0     14400000.0
1      8650000.0
2      8200000.0
3      8700000.0
4      9500000.0
5      9000000.0
6      8700000.0
7      8200000.0
8      9250000.0
9      8350000.0
10     7800000.0
11           NaN
12     7800000.0
13     7800000.0
14     8550000.0
Name: Price_numeric, dtype: float64

In [12]:
# 2. Extract ONLY the Date portion (Year, Month, Day) and ignore time & trailing text
def extract_date_only(val):
    if pd.isna(val):
        return pd.NaT
    # Matches patterns like '2026 Jun 05' from strings like '2026 Jun 05, 11:39 am'
    match = re.search(r'(\d{4}\s+[A-Za-z]+\s+\d{2})', str(val))
    if match:
        return match.group(1)
    return str(val)

df['Ad_Date_Clean_Str'] = df['Ad Date'].apply(extract_date_only)

# Convert to standard datetime with time entirely set to 00:00:00 (pure date)
df['Ad_Date_clean'] = pd.to_datetime(df['Ad_Date_Clean_Str'], format='mixed', errors='coerce').dt.normalize()

print("Sample Date-Only Column:")
print(df[['Ad Date', 'Ad_Date_clean']].head())

Sample Date-Only Column:
                 Ad Date Ad_Date_clean
0  2026 Jun 05, 11:39 am    2026-06-05
1  2026 Jun 06, 10:27 pm    2026-06-06
2   2026 Jul 19, 9:58 am    2026-07-19
3   2026 Jul 27, 5:36 pm    2026-07-27
4  2026 Jul 28, 12:06 am    2026-07-28

In [13]:
df.to_csv('formatted_data.csv', index=False)

In [14]:
df = pd.read_csv('formatted_data.csv')
df.head()

,Brand,Model,YOM,Mileage,Gear,Fuel Type,Engine (cc),Condition,Ad Date,Location,...,Number of Cylinders,Power Steering,Power Shutters,Power Mirrors,Manufacturing Country,Model_cleaned,Mileage_numeric,Price_numeric,Ad_Date_Clean_Str,Ad_Date_clean
0,Audi,A3 Sline,2018,93000.0,Automatic,Petrol,1000.0,Registered (Used),"2026 Jun 05, 11:39 am",Colombo,...,3.0,Yes,Yes,Yes,Germany,a3sline,93000.0,14400000.0,2026 Jun 05,2026-06-05
1,Audi,A1 Sline,2017,96000.0,Automatic,Petrol,990.0,Registered (Used),"2026 Jun 06, 10:27 pm",Kandy,...,3.0,Yes,Yes,Yes,Germany,a1sline,96000.0,8650000.0,2026 Jun 06,2026-06-06
2,Audi,A1 Highest Spec,2016,86000.0,Automatic,Petrol,10000.0,Registered (Used),"2026 Jul 19, 9:58 am",Colombo,...,6.0,Yes,Yes,Yes,Germany,a1highestspec,86000.0,8200000.0,2026 Jul 19,2026-07-19
3,Audi,A1,2017,69000.0,Automatic,Petrol,1000.0,Registered (Used),"2026 Jul 27, 5:36 pm",Bandaragama,...,3.0,Yes,Yes,Yes,Germany,a1,69000.0,8700000.0,2026 Jul 27,2026-07-27
4,Audi,A1,2016,55000.0,Automatic,Petrol,1000.0,Registered (Used),"2026 Jul 28, 12:06 am",Bandaragama,...,3.0,Yes,Yes,Yes,Germany,a1,55000.0,9500000.0,2026 Jul 28,2026-07-28

In [15]:
print(df['Gear'].unique())

['Automatic' 'Manual']

In [16]:
print(df['Condition'].unique())

['Registered (Used)' 'Unregistered (Recondition)' 'Brand New' 'Antique']

In [17]:
print(df['Location'].unique())

['Colombo' 'Kandy' 'Bandaragama' 'Dehiwala-Mount-Lavinia' 'Gampaha'
 'Horana' 'Jaffna' 'Kaduwela' 'Kiribathgoda' 'Kottawa' 'Maharagama'
 'Matugama' 'Nawala' 'Negombo' 'Nugegoda' 'Wattala' 'Welisara' 'Veyangoda'
 'Galle' 'Ambalangoda' 'Kurunegala' 'Ja-Ela' 'Matale' 'Battaramulla'
 'Kadawatha' 'Kelaniya' 'Kotte' 'Kuliyapitiya' 'Matara' 'Moratuwa'
 'Nittambuwa' 'Panadura' 'Piliyandala' 'Rajagiriya' 'Wennappuwa'
 'Nattandiya' 'Malabe' 'Kandana' 'Batticaloa' 'Ratnapura' 'Bandarawela'
 'Boralesgamuwa' 'Dompe' 'Embilipitiya' 'Homagama' 'Puttalam' 'Kegalle'
 'Minuwangoda' 'Kalutara' 'Kesbewa' 'Tangalle' 'Anuradapura' 'Dambulla'
 'Katunayake' 'Badulla' 'Dankotuwa' 'Pannipitiya' 'Hambantota' 'Mannar'
 'Ragama' 'Ampara' 'Avissawella' 'Gampola' 'Moneragala' 'Mirigama'
 'Polonnaruwa' 'Hatton' 'Mawanella' 'Polgahawela' 'Elpitiya' 'Kotikawatta'
 'Eheliyagoda' 'Ganemulla' 'Harispattuwa' 'Kolonnawa' 'Sammanthurai'
 'Trincomalee' 'Vavuniya' 'Warakapola' 'Chilaw' 'Hikkaduwa' 'Nawalapitiya'
 'Nuwara-Eliya' 'Beruwala' 'Divulapitiya' 'Hanwella' 'Pannala' 'Balangoda'
 'Kalmunai' 'Weligama' 'Kadugannawa' 'Mulleriyawa' 'Bentota' 'Marawila'
 'Ruwanwella' 'Wattegama' 'Ambanpola' 'Padukka' 'Kilinochchi' 'Daluguma'
 'Mahiyanganaya' 'Middeniya' 'Welimada' 'Dehiowita' 'Haputale' 'Koggala'
 'Eravur' 'Kataragama' 'horana' 'Peliyagoda']

In [18]:
print(df['Brand'].unique())

['Audi' 'BMW' 'Honda' 'Jaguar' 'Mazda' 'Mercedes-Benz' 'Mitsubishi'
 'Nissan' 'Suzuki' 'Toyota' 'Volvo']

In [19]:
print(df['Manufacturing Country'].unique())

['Germany' 'Thailand' 'Japan' 'United Kingdom' 'Indonesia' 'India'
 'Sweden' 'Belgium' 'Netherlands']

In [20]:
print(df['Body Type'].unique())

['Sedan' 'Hatchback' 'SUV' 'Minivan']

In [21]:
print(df['Fuel Type'].unique())

['Petrol' 'Hybrid' 'Diesel' 'Electric']